spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/weather}
    username: ${DB_USERNAME:weather}
    password: ${DB_PASSWORD:weather}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  web:
    resources:
      cache:
        period: 3600

server:
  port: 8080
